## Draft-2 simulation designs.
## Four models M1-M4 share the active set A = {1,2,3,4}.  The slowly varying
## factors follow Gardes & Podgorny (2025, Section 4.3), with their
## covariate-dependent component B1'x adapted to depend on the inactive
## variables U5,...,U8 through the fixed symmetric combination
##   v(u) = 2.5 (u5 + u6 + u7 + u8)  in (0, 10),
## matching the range of B1'x = 5 x3 + 5 x4 in the original paper.
## Responses are generated by quantile inversion: Y = V^{-gamma} l(1/V, u),
## V ~ U(0,1), as in Gardes & Podgorny.

source("code/R/generate.R")  # ar1_gaussian, population_uniform_matrix

gamma_model2 <- function(u, model) {
  s4 <- rowSums(u[, 1:4, drop = FALSE])
  switch(model,
    M1 = 0.5 * exp(-s4),
    M2 = 0.5 * exp(-s4),
    M3 = 0.5 * exp(-0.5 * s4),
    M4 = 0.55 * exp(-0.35 * s4 - 0.20 * u[, 1] * u[, 2] -
                    0.15 * u[, 3] * u[, 4]),
    stop("unknown model"))
}

## v(u): fixed pre-specified combination of the inactive variables 5:8.
sv_combination <- function(u) 2.5 * rowSums(u[, 5:8, drop = FALSE])

## Slowly varying factors evaluated at s = 1/V (upper-quantile argument).
## l1(s, v) = 1 / (1 + exp(v - s)),   l1 -> 1 as s -> Inf.
## l2(s, v) = exp(-1/(2s)) * v,       l2 -> v as s -> Inf.
response2 <- function(gamma, v_sv, model, V = runif(length(gamma))) {
  stopifnot(all(gamma > 0), all(v_sv > 0), length(v_sv) == length(gamma))
  s <- 1 / V
  ell <- if (model == "M2") exp(-V / 2) * v_sv
         else 1 / (1 + exp(v_sv - pmin(s, 700)))  # exp overflow guard; s>700 => l1=1
  y <- V^(-gamma) * ell
  stopifnot(all(is.finite(y)), all(y > 0))
  y
}

## Full-matrix dataset for the method-comparison experiment.
simulate_dataset2 <- function(n, p, rho, model, seed, block_size = 256L) {
  set.seed(seed)
  z <- ar1_gaussian(n, p, rho, block_size)
  u <- population_uniform_matrix(z)
  gamma <- gamma_model2(u, model)
  y <- response2(gamma, sv_combination(u), model)
  list(z = z, u = u, y = y, gamma = gamma)
}

## Streaming scorer for large tuning/sensitivity grids (our method only).
simulate_score_streaming2 <- function(n, p, rho, model, seed, h, alpha,
                                      epsilon = .05, block_size = 256L) {
  stopifnot(p >= 8L)
  set.seed(seed)
  innovation_sd <- sqrt(1 - rho^2)
  scores <- numeric(p); under_rate <- numeric(p)
  mean_local_n <- numeric(p); mean_local_k <- numeric(p)

  initial <- matrix(NA_real_, n, 8L)
  initial[, 1L] <- rnorm(n)
  for (j in 2:8)
    initial[, j] <- rho * initial[, j - 1L] + innovation_sd * rnorm(n)
  u_initial <- population_uniform_matrix(initial)
  gamma <- gamma_model2(u_initial, model)
  y <- response2(gamma, sv_combination(u_initial), model)

  score_block <- function(z, indices) {
    dg <- vapply(seq_along(indices), function(q)
      score_coordinate_cpp(z[, q], y, h, alpha, epsilon), numeric(5))
    scores[indices] <<- dg["score", ]
    under_rate[indices] <<- dg["under_rate", ]
    mean_local_n[indices] <<- dg["mean_local_n", ]
    mean_local_k[indices] <<- dg["mean_local_k", ]
  }
  score_block(initial, 1:8)
  previous <- initial[, 8L]
  rm(initial, u_initial)
  if (p > 8L) {
    for (start in seq.int(9L, p, by = block_size)) {
      end <- min(p, start + block_size - 1L)
      z <- matrix(NA_real_, n, end - start + 1L)
      for (q in seq_len(ncol(z))) {
        z[, q] <- rho * previous + innovation_sd * rnorm(n)
        previous <- z[, q]
      }
      score_block(z, start:end)
    }
  }
  list(scores = scores, under_rate = under_rate, mean_local_n = mean_local_n,
       mean_local_k = mean_local_k, y_min = min(y),
       y_finite = all(is.finite(y)), gamma_range = range(gamma))
}
