args<-commandArgs(trailingOnly=TRUE);stopifnot(length(args)==1L)
odir<-args[1];raw<-read.csv(file.path(odir,"replicate_metrics.csv"))
pdf(file.path(odir,"sure_screening_vs_p.pdf"),width=6.4,height=4.5)
par(mar=c(4.4,5.4,1.2,1.0))
md<-subset(raw,model=="A"&rho==0&a==.2&b==.2&p%in%c(100,500,1000,5000,10000))
ag<-aggregate(md$max_active_rank<=20,list(n=md$n,p=md$p),mean)
plot(range(ag$p),c(0,1),type="n",log="x",xaxt="n",xlab="Ambient dimension p",ylab="Sure-screening probability (d=20)")
axis(1,at=c(100,500,1000,5000,10000),labels=c("100","500","1000","5000","10000"))
for(nn in sort(unique(ag$n))) {w<-ag[ag$n==nn,];w<-w[order(w$p),];lines(w$p,w$x,type="b",pch=match(nn,sort(unique(ag$n))))}
legend("bottomleft",legend=paste0("n=",sort(unique(ag$n))),
       pch=seq_along(unique(ag$n)),lty=1,bty="n");dev.off()
pdf(file.path(odir,"sure_screening_vs_rho.pdf"),width=6.4,height=4.5)
par(mar=c(4.4,5.4,1.2,1.0))
dd<-subset(raw,model=="A"&n==1000&p==1000&a==.2&b==.2);ag<-aggregate(dd$max_active_rank<=20,list(rho=dd$rho),mean)
plot(ag$rho,ag$x,type="b",ylim=c(0,1.02),xlim=c(0,.75),xaxt="n",xlab=expression(rho),ylab="Sure-screening probability (d=20)",pch=19)
axis(1,at=c(0,.25,.5,.75),labels=c("0",".25",".50",".75"));dev.off()
pdf(file.path(odir,"sensitivity_heatmap.pdf"),width=7,height=5)
ss<-subset(raw,model=="A"&n==500&p==100&rho==0);ag<-aggregate(ss$max_active_rank<=20,list(a=ss$a,b=ss$b),mean)
aa<-sort(unique(ag$a));bb<-sort(unique(ag$b));zz<-outer(aa,bb,Vectorize(function(x,y)ag$x[ag$a==x&ag$b==y][1]))
cols<-hcl.colors(20,"YlOrRd",rev=TRUE)
layout(matrix(c(1,2),nrow=1),widths=c(5,1))
par(mar=c(4.2,4.2,2,.8))
image(aa,bb,zz,xlab="tail exponent a",ylab="bandwidth exponent b",col=cols,
      main="Sure-screening probability (d=20)")
for(i in seq_along(aa)) for(j in seq_along(bb))
 text(aa[i],bb[j],sprintf("%.2f",zz[i,j]),cex=.72)
par(mar=c(4.2,1.2,2,3.2))
zseq<-seq(min(zz),max(zz),length.out=20)
image(1,zseq,matrix(zseq,nrow=1),col=cols,axes=FALSE,xlab="",ylab="")
axis(4,las=1);mtext("probability",side=4,line=2.2)
dev.off()
cat("PASS final figures\n")
