#!/usr/bin/env python3
"""Build the single-file Bernoulli submission from the v2 sources.

Bernoulli requires the manuscript as one .tex document ("Please do not use
\\input{...} to include other tex files"), so this script inlines every
\\input recursively and wraps the result in the imsart [bj] frontmatter.

Run from the repository root or from manuscript/bernoulli:
    python3 manuscript/bernoulli/build_bj.py
"""
import re
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
MS = HERE.parent                      # manuscript/
OUT = HERE / "main-bj.tex"

INPUT_RE = re.compile(r"^[ \t]*\\input\{([^}]+)\}[ \t]*$", re.M)


def inline(path: pathlib.Path, depth: int = 0) -> str:
    """Recursively inline \\input{...}, resolving relative to manuscript/."""
    if depth > 5:
        raise RuntimeError(f"\\input nesting too deep at {path}")
    text = path.read_text(encoding="utf-8")

    def repl(m):
        target = m.group(1)
        cand = MS / target
        if cand.suffix != ".tex":
            cand = cand.with_suffix(".tex")
        if not cand.exists():
            raise FileNotFoundError(f"{cand} (from {path})")
        body = inline(cand, depth + 1).rstrip()
        return f"%% <<< {target}\n{body}\n%% >>> {target}"

    return INPUT_RE.sub(repl, text)


PREAMBLE = r"""%% Bernoulli [BJ] submission -- single-file build.
%% GENERATED by manuscript/bernoulli/build_bj.py from manuscript/sections-v2/.
%% Edit the sources in manuscript/sections-v2/, then re-run the script.
\documentclass[bj,authoryear]{imsart}

%% imsart loads natbib itself; do not load it again.
%% authoryear matches the Bernoulli template default and supports the
%% \citet{...} calls used in the prose (imsart-number.bst does not).
\usepackage{amsmath,amssymb,amsthm,mathtools,bm,booktabs,graphicx}
\usepackage{microtype}
\usepackage[section]{placeins}
\graphicspath{{../}}

\startlocaldefs
\theoremstyle{plain}
\newtheorem{theorem}{Theorem}[section]
\newtheorem{proposition}[theorem]{Proposition}
\newtheorem{corollary}[theorem]{Corollary}
\newtheorem{lemma}[theorem]{Lemma}
\DeclareMathOperator*{\esssup}{ess\,sup}
\DeclareMathOperator*{\argmax}{arg\,max}
\newcommand{\A}{A}\newcommand{\I}{I_\varepsilon}
\newcommand{\M}{\mathcal{M}}\newcommand{\Pp}{\mathbb P}
\newcommand{\E}{\mathbb E}\newcommand{\R}{\mathbb R}
\newcommand{\gmax}{\gamma^\star}
\endlocaldefs

\begin{document}

\begin{frontmatter}
\title{Tail-Index Sure Independence Screening for
High-Dimensional Heavy-Tailed Regression}
\runtitle{Tail-Index Sure Independence Screening}

%% Affiliations: Podgorny per alexpodgorny.fr (postdoc, ENSAI Rennes and
%% IRMAR UMR 6625, equipe de statistique); Pommeret per his public profile
%% (LISN, Universite Paris-Saclay/CNRS). Confirm before submission.
\begin{aug}
\author[A]{\inits{A.}\fnms{Alex}~\snm{Podgorny}\ead[label=e1]{alex.podgorny@univ-rennes2.fr}}
\author[B]{\inits{L.}\fnms{Luc}~\snm{Pommeret}\ead[label=e2]{luc.pommeret@universite-paris-saclay.fr}}
\address[A]{ENSAI and IRMAR (UMR CNRS 6625), Universit\'e de Rennes\printead[presep={,\ }]{e1}}
\address[B]{LISN, Universit\'e Paris-Saclay, CNRS\printead[presep={,\ }]{e2}}
\end{aug}

\begin{abstract}
%%ABSTRACT%%
\end{abstract}

\begin{keyword}
\kwd{conditional tail index}
\kwd{sure independence screening}
\kwd{high-dimensional regression}
\kwd{heavy tails}
\kwd{Hill estimator}
\kwd{regular variation}
\end{keyword}

\end{frontmatter}
"""

BACKMATTER = r"""
\bibliographystyle{imsart-nameyear}
\bibliography{../references}

\end{document}
"""


def main() -> None:
    src = (MS / "main-v2.tex").read_text(encoding="utf-8")

    m = re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", src, re.S)
    if not m:
        raise RuntimeError("abstract not found in main-v2.tex")
    abstract = m.group(1).strip()

    body_order = ["introduction", "model_population", "estimation_theory",
                  "computation_simulation", "real_data", "discussion"]
    parts = []
    for i, name in enumerate(body_order):
        parts.append(inline(MS / "sections-v2" / f"{name}.tex"))
        if name in ("computation_simulation", "real_data"):
            parts.append(r"\FloatBarrier")

    appendix = "\n".join(inline(MS / "sections-v2" / f"{n}.tex")
                         for n in ("appendix_aux", "appendix_proofs", "appendix_primitive"))

    out = (PREAMBLE.replace("%%ABSTRACT%%", abstract)
           + "\n" + "\n\n".join(parts)
           + "\n\n\\begin{appendix}\n" + appendix + "\n\\end{appendix}\n"
           + BACKMATTER)

    OUT.write_text(out, encoding="utf-8")
    n_inputs = out.count("%% <<< ")
    print(f"wrote {OUT.relative_to(MS.parent)} "
          f"({len(out.splitlines())} lines, {n_inputs} files inlined)")


if __name__ == "__main__":
    main()
